language: node_js
node_js:
   - "0.10"
   - "0.12"
   - "4.2"
addons:
  postgresql: "9.4"
env:
  global:
    - MYSQL_HOST=localhost
    - MYSQL_DATABASE=test_db
    - MYSQL_USER=root
    - MYSQL_PASSWORD=
    - POSTGRES_HOST=localhost
    - POSTGRES_DATABASE=test_db
    - OOSTGRES_USER=postgres
    - POSTGRES_PASSWORD=
before_script:
  - mysql -e 'create database test_db;'
  - psql -c 'create database test_db;' -U postgres
after_success:
   - COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=7lmtywEWb8VitLviZro6EfJTu4Kfy0mXI node_modules/.bin/builder -c test --coverage --coveralls
