language: node_js
node_js:
  - "0.10" # from 2013-03 maintenance till 2016-10
  - "0.12" # from 2015-02 maintenance till 2016-12
  - "4"  # LTS   from 2015-10 maintenance till 2018-04
  - "6"  # LTS   from 2016-10 maintenance till 2019-04
#  - "7"  # devel from 2016-10
env:
  global:
    - MYSQL_HOST=localhost
    - MYSQL_DATABASE=test_db
    - MYSQL_USER=root
    - MYSQL_PASSWORD=
    - POSTGRES_HOST=localhost
    - POSTGRES_DATABASE=test_db
    - OOSTGRES_USER=postgres
    - POSTGRES_PASSWORD=
    # Fix the c++ compiler on Ubuntu 14.04
    - CXX=g++-4.8
addons:
  postgresql: "9.4"
  # Fix the c++ compiler on Ubuntu 14.04
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - mysql -e 'create database test_db;'
  - psql -c 'create database test_db;' -U postgres
after_success:
   - COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=7lmtywEWb8VitLviZro6EfJTu4Kfy0mXI node_modules/.bin/builder test --coveralls
